# Generated by Django 2.2 on 2019-05-23 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profilemanager', '0001_initial'),
        ('postmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2019, 5, 23, 13, 9, 7, 653197, tzinfo=utc))),
                ('updated_on', models.DateTimeField(default=datetime.datetime(2019, 5, 23, 13, 9, 7, 653233, tzinfo=utc))),
                ('post_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('make_public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profilemanager.Profile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postmanager.Category')),
                ('tags', models.ManyToManyField(to='postmanager.Tag')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
