# Generated by Django 2.2 on 2019-05-24 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postmanager', '0002_auto_20190523_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='make_public',
            new_name='public_visible',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 11, 37, 0, 724775, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 11, 37, 0, 724808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='postmanager.Post')),
            ],
        ),
    ]
