# Generated by Django 2.2 on 2019-05-24 13:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postmanager', '0004_auto_20190524_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 13, 7, 29, 639991, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 13, 7, 29, 640023, tzinfo=utc)),
        ),
    ]
