# Generated by Django 2.2 on 2019-05-24 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('postmanager', '0005_auto_20190524_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 13, 11, 36, 850785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='postmanager.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 13, 11, 36, 850816, tzinfo=utc)),
        ),
    ]
