# Generated by Django 2.2 on 2019-05-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmanager', '0007_auto_20190527_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='postmanager.Tag'),
        ),
    ]
